### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [sudolabs-io/gtm-instyle#1]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) encodeUriComponent should be used on user provided values that are then used as parameters in your url. These methods take in a single text argument and return a URI Encoded string. You should use this method on data.clientId when generating the url
const API_URL = "https://static.instyle.ai/gtm/pdp/" + data.clientId + ".js";

**Comment by selrond** [comment]
@praveena-pappu fixed in ed8950b, thanks
